import { useState } from 'react';
import { Megaphone, Users, TrendingUp, Sparkles, Send, Gift, Target, ArrowRight, CheckCircle2, Zap } from 'lucide-react';
import AIBadge from '../../components/common/AIBadge';
import ProgressBar from '../../components/common/ProgressBar';

const campaigns = [
  { id: 'CAMP001', name: 'Win-Back Warriors', type: 'Win-Back', target: 'Churned 30+ days (42 members)', message: 'We miss you! Come back for 50% off your first month + free PT session.', status: 'Active', sent: 42, opened: 28, converted: 9, revenue: 22491 },
  { id: 'CAMP002', name: 'Bring A Friend', type: 'Referral', target: 'Active Premium+ members (180)', message: 'Refer a friend, get 1 month free. They join, you both win!', status: 'Draft', sent: 0, opened: 0, converted: 0, revenue: 0 },
  { id: 'CAMP003', name: 'Class Fill Friday', type: 'Class Boost', target: 'Underbooked classes (3)', message: 'Flash sale: All classes this Friday at ₹149! Limited spots.', status: 'Scheduled', sent: 0, opened: 0, converted: 0, revenue: 0 },
  { id: 'CAMP004', name: 'Elite Upgrade Path', type: 'Upsell', target: 'Premium members > 6 months (120)', message: 'Ready for more? Upgrade to Elite and get unlimited classes + priority booking.', status: 'Active', sent: 120, opened: 85, converted: 14, revenue: 55986 },
];

const abTests = [
  { name: 'Win-Back Subject Line', variantA: '"We miss you at IronForge"', variantB: '"Your free PT session is waiting"', winner: 'B (42% > 28% open rate)', improvement: '+50%' },
  { name: 'Referral Reward', variantA: '1 month free', variantB: '₹500 cashback', winner: 'A (35% > 22% click-through)', improvement: '+59%' },
];

export default function MarketingCampaigns() {
  const [launchedIds, setLaunchedIds] = useState<Record<string, boolean>>({});
  const [selectedCampaign, setSelectedCampaign] = useState<string | null>(null);

  const handleLaunch = (id: string) => {
    setLaunchedIds(prev => ({...prev, [id]: true}));
  };

  const statusColors: Record<string, string> = {
    Active: 'bg-[#2E7D32]/10 text-[#2E7D32]',
    Draft: 'bg-[#6E625D]/10 text-[#6E625D]',
    Scheduled: 'bg-[#F9A825]/10 text-[#F9A825]',
  };

  return (
    <div className="animate-fadeIn space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-extrabold text-[#231815]">AI Marketing Campaigns</h2>
          <p className="text-sm text-[#6E625D] mt-1">Win-back, referral, upsell, and class-fill campaigns — auto-generated by AI</p>
        </div>
        <AIBadge text="4 Campaigns" />
      </div>

      {/* Campaign Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {[
          { label: 'Active Campaigns', value: '2', icon: Megaphone, color: '#E00026' },
          { label: 'Total Sent', value: '162', icon: Send, color: '#F9A825' },
          { label: 'Conversions', value: '23', icon: TrendingUp, color: '#2E7D32' },
          { label: 'Revenue Generated', value: '₹78.5K', icon: Gift, color: '#E00026' },
        ].map((stat, i) => (
          <div key={i} className="card p-4 flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: `${stat.color}15` }}>
              <stat.icon className="w-5 h-5" style={{ color: stat.color }} />
            </div>
            <div>
              <p className="text-lg font-extrabold text-[#231815]">{stat.value}</p>
              <p className="text-[11px] text-[#6E625D]">{stat.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Campaigns */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {campaigns.map(camp => {
          const isLaunched = launchedIds[camp.id] || camp.status === 'Active';
          return (
            <div key={camp.id} className={`card p-5 hover:shadow-md transition-shadow cursor-pointer ${selectedCampaign === camp.id ? 'ring-2 ring-[#E00026]' : ''}`}
              onClick={() => setSelectedCampaign(selectedCampaign === camp.id ? null : camp.id)}>
              <div className="flex items-start justify-between mb-3">
                <div>
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-bold text-[#231815]">{camp.name}</p>
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-md ${statusColors[isLaunched ? 'Active' : camp.status]}`}>
                      {isLaunched ? 'Active' : camp.status}
                    </span>
                  </div>
                  <p className="text-[10px] text-[#6E625D] uppercase tracking-wider mt-0.5">{camp.type}</p>
                </div>
                {camp.revenue > 0 && <p className="text-lg font-extrabold text-[#2E7D32]">+₹{camp.revenue.toLocaleString()}</p>}
              </div>
              <p className="text-[11px] text-[#6E625D] mb-2">🎯 {camp.target}</p>
              <p className="text-[11px] text-[#E00026] bg-[#E00026]/5 p-2 rounded-lg">"{(camp as any).message}"</p>
              {camp.sent > 0 && (
                <div className="mt-3 space-y-2">
                  <div className="flex justify-between text-[10px]"><span className="text-[#6E625D]">Opens</span><span className="font-semibold text-[#231815]">{camp.sent > 0 ? Math.round(camp.opened/camp.sent*100) : 0}%</span></div>
                  <ProgressBar value={camp.sent > 0 ? Math.round(camp.opened/camp.sent*100) : 0} size="sm" color="#E00026" />
                  <div className="flex justify-between text-[10px]"><span className="text-[#6E625D]">Conversions</span><span className="font-semibold text-[#2E7D32]">{camp.converted} members</span></div>
                </div>
              )}
              {selectedCampaign === camp.id && !isLaunched && (
                <button onClick={() => handleLaunch(camp.id)} className="btn-primary text-xs w-full mt-3 animate-fadeIn">
                  🚀 Launch Campaign
                </button>
              )}
              {launchedIds[camp.id] && camp.status === 'Draft' && (
                <p className="text-[10px] text-[#2E7D32] mt-2 animate-fadeIn">✓ Campaign launched! Emails sending to {camp.target.match(/\d+/)?.[0] || 0} members.</p>
              )}
            </div>
          );
        })}
      </div>

      {/* A/B Test Results */}
      <div className="card p-6">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-[#E00026]" />
          <h3 className="text-sm font-bold text-[#231815]">AI A/B Test Results</h3>
          <AIBadge text="Auto-Optimized" />
        </div>
        <div className="space-y-3">
          {abTests.map((test, i) => (
            <div key={i} className="p-4 bg-[#F5F0EA] rounded-xl">
              <p className="text-xs font-bold text-[#231815] mb-2">{test.name}</p>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-2 bg-white rounded-lg">
                  <p className="text-[10px] text-[#6E625D]">Variant A</p>
                  <p className="text-[11px] font-semibold text-[#231815]">{test.variantA}</p>
                </div>
                <div className="p-2 bg-[#2E7D32]/5 rounded-lg border border-[#2E7D32]/20">
                  <p className="text-[10px] text-[#2E7D32]">Winner B ↑</p>
                  <p className="text-[11px] font-semibold text-[#2E7D32]">{test.variantB}</p>
                </div>
              </div>
              <p className="text-[10px] text-[#6E625D] mt-2">🏆 {test.winner} ({test.improvement} improvement)</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
